# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_flatten"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2026, John S. Urban"
description = "create a rank one array pointer to a scalar or multi-dimensional array"
categories = ["pack, flatten, dimension"]
keywords = ["fortran", "array" ]
homepage = "https://github.com/urbanjost/M_flatten.git"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false
[install]
   library = false
   test = false
[fortran]
   implicit-typing = false
   #implicit-external = false
   implicit-external = true
   source-form = "free"

[[test]]
   name="runTests"
   source-dir="test/"
   main="test_suite_M_flatten.f90"
   [test.dependencies]
   M_framework    = { git = "https://github.com/urbanjost/M_framework.git" }
   #M_framework = {namespace = "GPF"}
   # ln -f -s $HOME/github/GLINKS GLINKS
   #M_framework  = { path = "GLINKS/M_framework" }
